### ISSUE TITLE
Running Demo on Win64 requires PATH setting

### ISSUE THREAD

**Issue by stuhssn** [epsilonlabs/emc-simulink#4]
Running the demo on win64 installations requires the _matlabroot_\bin\win64 folder to be on the Windows PATH, otherwise there is an error raised : "UnsatisfiedLinkError: C:\Program Files\MATLAB\R2016b\bin\win64\nativemvm.dll: Can't find dependent libraries"

**Comment by kolovos** [comment]
Is this necessary even if you've added the `-Djava.library.path=<matlab-root>/bin/win64` VM argument? The driver seems to be working well on my Windows machine and the folder is not in the PATH.

**Comment by kolovos** [comment]
Instructions updated in 928539b
